a = {
    "dossierNo": "测试 3567",
    "orderDate": "2021-03-03",
    "supCode": "0000335",
    "supName": "佛山市禅城区南庄镇梧村集团有限公司",
    "planDateSt": "2020-10-20",
    "planDateEnd": "2021-03-13",
    "companyCode": "101",
    "companyName": "广东新明珠陶瓷集团有限公司",
    "matTypeCode": "ctp001",
    "matTypeName": "五金件采购",
    "status": "Draft",
    "versionNo": "1.0",
    "remark": "23",
    "currencyCode": "RMB",
    "factoryCodes": "21001,21003,21101",
    "factoryNames": "江西一厂,江西二厂,湖北新明珠绿色建材科技有限公司",
    "depotCodes": "HBWJ,JXGF,JXWJ1",
    "depotNames": "湖北新明珠绿色建材五金仓,江西新明珠建材工服仓,江西新明珠建材壹厂五金仓",
    "contractDescribe": "12",
    "deposit": "Y",
    "depositName": "是",
    "contractCategoryCode": "original",
    "contractCategoryName": "原件合同",
    "contractTypeCode": "year",
    "contractTypeName": "年度合同",
    "paymentCode": "ElectronicBankAcceptanceBill",
    "paymentName": "电子银行承兑汇",
    "settlementCode": "ConfirmOrder",
    "settlementName": "对单后",
    "settlementDay": "90",
    "rateCode": "thirteen",
    "rateName": "13",
    "contractSignedDate": "2020-05-20",
    "outCarton": "N",
    "outCartonName": "否",
    "factoryDepot": "24,22,14,13",
    "creator": "1010537",
    "creatorName": "肖建文",
    "createTime": "2021-03-01 16:03:52",
    "modifier": "0",
    "removed": "false",
    "matClick": "Matgroup",
    "skipWarn": "true"
}

body = {
    "enclosureList": "[]",
    "detailsJson": "[]",
    "matgroupJson": "[]",
}

a = {
    'contractNo': 'PC210303012',
    'poContractNo': 'XMZ[2021]GYB-wjf070332',
    'dossierNo': '接口自动化生成-2021',
    'orderDate': '2021-03-03',
    'supCode': '0101353',
    'supName': '广东大华轴承有限公司',
    'planDateSt': '2020-10-20',
    'planDateEnd': '2021-03-13',
    'companyCode': '101',
    'companyName': '广东新明珠陶瓷集团有限公司',
    'matTypeCode': 'ctp001',
    'matTypeName': '五金件采购',
    'status': 'Submit',
    'versionNo': '1.0',
    'currencyCode': 'RMB',
    'factoryCodes': '20201',
    'factoryNames': '南庄三厂',
    'depotCodes': 'GLGF',
    'depotNames': '广东格莱斯工服仓',
    'contractDescribe': '接口自动化生成',
    'deposit': 'Y',
    'depositName': '是',
    'contractCategoryCode': 'original',
    'contractCategoryName': '原件合同',
    'contractTypeCode': 'year',
    'contractTypeName': '年度合同',
    'paymentCode': 'ElectronicBankAcceptanceBill',
    'paymentName': '电子银行承兑汇',
    'settlementCode': 'ConfirmOrder',
    'settlementName': '对单后',
    'settlementDay': '90',
    'rateCode': 'thirteen',
    'rateName': '13',
    'contractSignedDate': '2020-05-20',
    'outCarton': 'N',
    'outCartonName': '否',
    'factoryDepot': '14',
    'creator': 1000150,
    'creatorName': '肖建文',
    'createTime': '2021-03-03 11:35:52',
    'modifier': '0',
    'removed': 'false',
    "matClick": "Matgroup",
    "skipWarn": "true"
}
